### ISSUE TITLE
Manage flats on /houses

### ISSUE THREAD

**Issue by kh0ma** [ita-social-projects/Home#160]
**As a** cooperation administrator **I want to** have the ability to manage flats for the cooperation so I can edit, create or delete them. Also, I would like to assign or unassign a user for the flat.

### Description
After implementing https://github.com/ita-social-projects/Home/issues/97 we have the ability to manage houses for cooperation. Also, I would like to manage flats so I can create a flat and assign a user for this flat. Please provide API for it.

### Acceptance Criteria
I have enough API for managing flats for cooperation. 

### Epic link
Epic #3 
[ZenHub Epic](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/home/159)

### Tasks 
- [ ] Add changes to OpenAPI spec.
- [ ] Add API tests.
- [ ] Add implementation ( service layer, domain layer, DB migrations).
- [ ] Check all tests.

**Comment by AleksLen** [comment]
https://docs.google.com/document/d/1Cy9WT6Pwpa4bCdhBRsZtydUhN9hXa0BB_xRG21UUy0M/edit#
