### ISSUE TITLE
Introduce Query Service

### ISSUE THREAD

**Issue by mykytam** [ita-social-projects/Home#71]
**As a** user **I want to** pass in query parameters in the url **so that** I could get a valid JSON document.

**Description**
- It should be useful not only for REST, but also for other services, i.e. it can be used for querying the necessary data. For example we provide a class by which we can search (a map with parameters).
- The list of available parmeters per Entiry must be described by the config.
- Default parameters for each Entity - sort, page_size, page_number and id.
- Changes in API design - defaults parameters are added to all queries. Also added are query parameters available for a query regarding this Entity. The query parameters available for this query regarding this Entity are also added.
- Query parameter _search is added.
- The sort parameter must be able to change the behaviour - ascending/descending.
- The search parameter should only work with the available query parameters.
- Without headers API paging is impossible.

### Acceptance Criteria
In result of passing in the query parameters, JSON file with data (that is quered by the parameters that was passed) returns as a response

**Epic link**
Home project API MVP #55 [Epic](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/home/55)

### Tasks 
- [ ] service can be used for querying the data.
- [ ] describe parameters per Entity in the config.
- [ ] add default parameters for each Entity.
- [ ] defaults parameters are added to all queries.
- [ ] add query parameter _search.
- [ ] add ascending/descending behaviour in sort.
- [ ] limit the use of search only with the available query parameters.
- [ ] prohibit paging without headers.
