### ISSUE TITLE
Update README of the project

### ISSUE THREAD

**Issue by mykytam** [ita-social-projects/Home#78]
**As a** user or developer,  **I want to** get clear and up-to-date documentation  **so that** I could get an overall idea of the project.

**Description**
Update project's README.
Add additional package in the project for documentation.
Make .github templates more standard.

### Acceptance Criteria
Every user or newbie can get an idea of the project's API, installation, secrets, and usage.

**Epic link**
Epic #3 
[ZenHub Epic](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/home/3)

### Tasks 
- [x] update README.md.
- [x] create new module for docs.
- [x] update .github templates.
